default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: 'hoangtoni8'

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'rails_store_development' %>

test:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'rails_store_test' %>

production:
  <<: *default
  database: rails_store_production
  password: <%= ENV['RS_DATABASE_PASSWORD'] %>
